# Generated by Django 4.0.6 on 2022-12-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='null', max_length=30, verbose_name='用户名')),
                ('userPassword', models.CharField(default='123456', max_length=25, verbose_name='用户密码')),
                ('userEmail', models.CharField(default='', max_length=30, verbose_name='用户邮箱')),
                ('userPortrait', models.CharField(default='', max_length=25, verbose_name='用户头像的存储路径')),
                ('userPrefer', models.CharField(default='', max_length=25, verbose_name='用户的口味偏好')),
                ('userExpense', models.FloatField(default=0.0, verbose_name='用户的支出金额')),
            ],
            options={
                'db_table': 'backend_user',
            },
        ),
    ]
