# Generated by Django 4.0.6 on 2022-12-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activityContent',
            field=models.CharField(max_length=300, verbose_name='活动详情'),
        ),
    ]
