# Generated by Django 4.0.6 on 2022-12-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogLabel',
            field=models.CharField(max_length=30, null=True, verbose_name='标签'),
        ),
    ]
