# Generated by Django 4.0.6 on 2022-12-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogDeliverTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='帖子发布时间'),
        ),
    ]
