# Generated by Django 4.0.6 on 2022-11-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='用户名')),
                ('dept', models.CharField(blank=True, max_length=30, null=True, verbose_name='系名')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
