# Generated by Django 4.0.6 on 2022-12-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_activity_activitycontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifyUserFavoriteDishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantName', models.CharField(max_length=30, verbose_name='所属商家名称')),
                ('dishesCnt', models.IntegerField(default=0, verbose_name='收藏菜品数')),
            ],
        ),
    ]
