# Generated by Django 4.0.6 on 2022-11-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_user_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterModelTable(
            name='user',
            table='backend_user',
        ),
    ]
