# Generated by Django 4.0.6 on 2022-12-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_blog_blogdelivertime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitycomment',
            name='commentSort',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='commentSort',
        ),
        migrations.RemoveField(
            model_name='dishcomment',
            name='commentSort',
        ),
        migrations.AlterField(
            model_name='activitycomment',
            name='commentDeliverTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='commentDeliverTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='dishcomment',
            name='commentDeliverTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
