# Generated by Django 4.0.6 on 2022-12-23 09:11

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_blog_bloglabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogPicture',
            field=models.ImageField(default='default.jpg', null=True, upload_to=app01.models.user_directory_path, verbose_name='活动头图'),
        ),
        migrations.AlterField(
            model_name='blogpicture',
            name='blogPicture',
            field=models.ImageField(default='default.jpg', null=True, upload_to='blogs/imgs', verbose_name='帖子照片'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dishPicture',
            field=models.ImageField(default='default.jpg', null=True, upload_to=app01.models.user_directory_path, verbose_name='菜品头像'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='userPortrait',
            field=models.ImageField(default='default.jpg', null=True, upload_to=app01.models.user_directory_path, verbose_name='用户头像'),
        ),
    ]
