# Generated by Django 4.0.6 on 2022-12-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_classifyuserfavoritedishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='isMerchant',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, verbose_name='是否是商家'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchant',
            name='isMerchant',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, verbose_name='是否是商家'),
        ),
    ]
