# Generated by Django 4.0.6 on 2022-11-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_user_dept_remove_user_name_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userExpense',
            field=models.FloatField(default=0.0, verbose_name='用户的支出金额'),
        ),
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(default='null', max_length=30, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='user',
            name='userPassword',
            field=models.CharField(default='123456', max_length=25, verbose_name='用户密码'),
        ),
        migrations.AddField(
            model_name='user',
            name='userPortrait',
            field=models.CharField(default='', max_length=25, verbose_name='用户头像的存储路径'),
        ),
        migrations.AddField(
            model_name='user',
            name='userPrefer',
            field=models.CharField(default='', max_length=25, verbose_name='用户的口味偏好'),
        ),
    ]
