# Generated by Django 4.0.6 on 2022-12-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_dish_dishstars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dishFollowerCnt',
            field=models.IntegerField(default=0, verbose_name='收藏人数'),
        ),
    ]
