# Generated by Django 4.0.6 on 2022-12-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_alter_dish_dishfollowercnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activityBegin',
            field=models.DateField(auto_now_add=True, verbose_name='活动开始时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityEnd',
            field=models.DateField(auto_now_add=True, verbose_name='活动结束时间'),
        ),
    ]
