# Generated by Django 4.0.6 on 2022-12-15 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app01', '0007_rename_launcher_activity_user_ab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycomment',
            name='commenter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='commenter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AlterField(
            model_name='dishcomment',
            name='commenter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='merchantFollowerCnt',
            field=models.IntegerField(default=0, verbose_name='收藏人数'),
        ),
    ]
