# Generated by Django 4.0.6 on 2022-12-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_activity_user_ab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='用户反馈')),
                ('commentDeliverTime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
        ),
    ]
